def xps():
	return ["PL", "Sênior", "SENIOR", "PLENO", "sr", "Junior", "SR", "Jr", "Senior", "JUNIOR", "JÚNIOR", "Pl", "pl", "Pleno", "Sr", "júnior","sênior", "pleno", "SÊNIOR", "JR", "senior", "Júnior", "estágio", "estagiário", "ESTÁGIO", "Estágio", "estagio", "Estagio", "ESTAGIO", "Estagiário", "ESTAGIÁRIO", "estagiario", "Estagiario", "ESTAGIARIO", "Especialista", "especialista", "IIII", "III", "II", "I"]

def titulos():
	return ["Analista de Dados", "Engenheiro de Dados", "Desenvolvedor de Dados", "Estagiário de Dados", "Arquiteto de Dados", "Administrador de Banco de Dados", "Especialista em Engenharia de Dados", "Cientista de Dados", "Analista BI", "Analista de Business Intelligence", "Analista de Business Analytics", "Analista de Inteligência de Negócios", "Engenheiro de Machine Learning", "Engenheiro de Big Data", "Analista de BI", "Desenvolvedor de Business Intelligence", "Especialista em Ciência de Dados", "Desenvolvedor de Data Science", "Cientista de Business Intelligence", "Analista de ETL", "Engenheiro de ETL", "Especialista em ETL", "Desenvolvedor de ETL", "Data Engineer", "Analytics engineer"]

def ferra():
	return ["Python", "R Studio", "SQL", "PySpark", "Polars", "Cassandra", "Google Analytics 4 (GA4)", "Apache Kafka", "Apache HBase", "Hive", "Impala", "Pig", "Airflow", "Apache NiFi", "Flink", "Apache Beam", "Apache Hadoop", "Amazon Redshift", "Microsoft Azure SQL Data Warehouse", "Apache Airflow", "Google BigQuery", "Oracle Database", "Amazon DynamoDB", "Couchbase", "Neo4j", "Microsoft Power BI", "Apache Flink", "Apache Storm", "Databricks", "MongoDB", "Looker", "Tableau", "Qlik Sense", "Excel", "PowerBI", "Google Data Studio", "D3.js", "Highcharts", "Plotly", "Matplotlib", "Seaborn", "Bokeh", "Metabase", "Google Sheets", "DataRobot", "H2O.ai", "Alteryx", "RapidMiner", "Excel Avançado", "Snowflake", "Teradata", "IBM Db2", "Exasol", "Amplitude", "MicroStrategy", "Sisense", "ThoughtSpot", "Pentaho", "Docker", "Cognos", "Yellowfin", "Spotfire", "Synapse", "Dataform", "KNIME", "Birst", "Splunk", "Elasticsearch", "Logstash", "Kibana", "Prometheus", "Grafana", "InfluxDB", "Datadog", "Mongo DB", "AWS", "Google Cloud", "Azure", "Kubernetes", "Linux", "Shell script", "JavaScript", "HTML", "CSS", "ReactJS", "NodeJS", "RESTful API", "JSON", "Pandas", "NumPy", "Jupyter", "GCP Dataflow", "AWS Glue", "Azure Data Factory", "Talend", "Jupyter notebook", "Dataiku", "Redshift", "Bigtable", "Firebase", "Cloud Spanner", "Workflow Orchestration", "Data Engineering", "BI Reporting", "Power Query", "Power Pivot", "GPC", "Looker Studio", "Fivetran", "Kedro", "Power BI", "GA4", "Qlik", "Hadoop", "Data Factory", "Couchbase", "CouchDB", "Couch DB", "Couch base", "RStudio", "Amazon DynamoDB", "Amazon Dynamo DB", "Google Cloud Firestore", "Apache HBase", "Amazon DocumentDB", "RethinkDB", "RavenDB", "Rethink DB", "Raven DB", "MySQL", "PostgreSQL", "Oracle", "SQL Server", "Power Automate", "SQLite", "MariaDB", "IBM Db2", "Microsoft Access", "Power Apps", "Amazon RDS", "Google Cloud SQL", "Azure SQL Database", "IBM Db2 on Cloud", "Dataplex", "Data catalog", "Java", "Scala", "Ruby", "Perl", "SAS", "SAP", "SSIS"]

def atividades():
	return ["Pipelines de Dados", "Modelagem de dados", "Arquitetura de Dados", "Teste de Hipóteses", "Mineração de Dados", "Limpeza de Dados", "Análise Exploratória de Dados", "Modelagem Estatística", "Modelagem Matemática", "Mineração de Texto", "Dashboard", "Machine Learning", "Governança de dados", "Modelagem Preditiva", "Fluxo de dados", "ETL", "BI Reporting", "Streaming Data", "Avaliação de Modelos", "Data Governance", "Data Quality", "Data pipeline", "Privacidade de Dados", "Análise de dados", "Visualização de dados", "Interpretação de dados", "Elaboração de relatórios", "Modelagem de dados", "Comunicar Resultados", "Deep Learning", "Big Data", "Ferramentas de ML/DL", "Estrutura de dados", "Segurança de dados", "Data Warehousing", "Integração de dados", "Automação", "Auditoria de Dados", "Previsão de Demanda", "Análise de Risco", "Análise de Custos", "Segmentação de Clientes", "Análise de Regressão", "Manutenção de Sistemas", "Ética de Dados", "Análise Preditiva", "Processamento de Linguagem Natural", "Análise de Séries Temporais", "Análise de Sentimento", "Validação de Modelos", "Experimentação", "Teste A/B", "Estatística", "Processamento de Dados"]

def social():
	return ["Boa comunicação", "Habilidades interpessoais", "Pensamento crítico", "Resolução de problemas", "Trabalho em equipe", "Gestão de tempo", "Gestão de Projetos", "Inteligência Emocional", "Adaptabilidade", "Aprendizagem Rápida", "Storytelling", "Ética de trabalho", "trabalhar sob pressão", "Flexibilidade", "Liderança", "Autonomia", "Iniciativa", "Curiosidade", "Comunicação Técnica", "Trabalho Colaborativo", "Gestão de Projetos", "Resolução de Conflitos", "Tomada de Decisão", "Aprendizado Contínuo", "Criatividade", "Planejamento Estratégico", "Pensamento Analítico", "Raciocínio Lógico", "Resiliência", "Empatia", "Gerenciamento de Stakeholders"]

def agil():
	return ["Scrum", "Kanban", "Lean", "Agile", "Ágil", "DevOps", "Waterfall", "Sprint", "XP (Extreme Programming)", "Feature-Driven Development (FDD)", "Test-Driven Development (TDD)", "Continuous Integration (CI)", "Continuous Deployment (CD)", "Pair Programming", "Rapid Application Development (RAD)", "Design Thinking", "Six Sigma", "ITIL (Information Technology Infrastructure Library)"]

def grad():
	return ["Ciência da Computação", "Engenharia da Computação", "Sistemas de Informação", "Matemática", "Física", "Ciência Contábeis", "Engenharia de Software", "Análise e Desenvolvimento de Sistemas", "Engenharia Elétrica", "Engenharia de Telecomunicações", "Engenharia de Controle e Automação", "Engenharia de Produção", "Tecnologia da Informação", "Ciência de Dados", "Administração", "Economia"]

def cont():
	return ["Pessoa Jurídica (PJ)", "CLT", "PJ"]

