name: Run Script Every Two Months

on:
  schedule:    
    - cron: '0 6 30 8 *'    
    - cron: '30 6 29 10 *'    
    - cron: '40 6 28 12 *'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "credentials.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}        
        TABLE_ID: ${{ secrets.TABLE_ID }}
        BACKUP_TABLE_ID: ${{ secrets.BACKUP_TABLE_ID }}
        ANALISTA_DADOS_KEY_API: ${{ secrets.ANALISTA_DADOS_KEY_API }}
        ANALISTA_BI_KEY_API: ${{ secrets.ANALISTA_BI_KEY_API }}
        CIENTISTA_DADOS_KEY_API: ${{ secrets.CIENTISTA_DADOS_KEY_API }}
        ENGENHEIRO_DADOS_KEY_API: ${{ secrets.ENGENHEIRO_DADOS_KEY_API }}
      run: |
        python backup/backup.py
