name: Deploy Streamlit App

on:
  workflow_dispatch:

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ajuste para a versão de Python necessária

      - name: Install Streamlit
        run: pip install requirements.txt

      - name: Set up environment variables
        run: echo "BIGQUERY=$BIGQUERY" >> $GITHUB_ENV

        env:
          BIGQUERY: ${{ secrets.BIGQUERY }}

      - name: Start Streamlit App
        run: |
          nohup streamlit run --server.headless true Panorama_das_Vagas_de_Dados.py &
          sleep 10
