name: Run Python Script

on:
  workflow_dispatch:

env:
  bigquery: ${{secrets.BIGQUERY}}

jobs:
  run-python:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Python Script
        run: |
          pip install requirements.txt
          python Panorama_das_Vagas_de_Dados.py

        
        
        
