name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "Printing environment variables"
          printenv
        env:
          BIGQUERY: ${{ secrets.BIGQUERY }}

      - name: Verify BIGQUERY Secret
        run: |
          echo "Verifying BIGQUERY secret"
          if [ -z "${{ secrets.BIGQUERY }}" ]; then
            echo "BIGQUERY secret is not set"
            exit 1
          else
            echo "BIGQUERY secret is set"
          fi

      - name: Run Python Script
        env:
          BIGQUERY: ${{ secrets.BIGQUERY }}
        run: |
          python Panorama_das_Vagas_de_Dados.py
