name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "Printing environment variables"
          printenv
        env:
          BIGQUERY: ${{ secrets.BIG_QUERY }}

      - name: Verify BIG_QUERY Secret
        run: |
          echo "Verifying BIG_QUERY environment variable"
          if [ -z "$BIG_QUERY" ]; then
            echo "BIG_QUERY is not set"
            exit 1
          else
            echo "BIG_QUERY is set"
          fi
        env:
          BIGQUERY: ${{ secrets.BIG_QUERY }}

      - name: Run Python Script
        env:
          BIGQUERY: ${{ secrets.BIG_QUERY }}
        run: |
          python Panorama_das_Vagas_de_Dados.py
