name: Deploy Streamlit App

on:
  workflow_dispatch:

env:
    TYPE: ${{ secrets.TYPE }} 
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}          
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    AUTH_URI: ${{ secrets.AUTH_URI }}
    TOKEN_URI: ${{ secrets.TOKEN_URI }}
    AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
    CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
    UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }} 
        

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install Streamlit
        run: pip install -r requirements.txt        

      - name: Start Streamlit App
        run: |
          nohup streamlit run --server.headless true Panorama_das_Vagas_de_Dados.py &
          sleep 10
