name: Deploy Streamlit App

on:
  workflow_dispatch:

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Ajuste para a versão de Python necessária

      - name: Install Streamlit
        run: pip install streamlit

      - name: Start Streamlit App
        run: |
          nohup streamlit run app.py &  # Inicia o Streamlit em segundo plano
          sleep 10  # Espera um tempo para o Streamlit iniciar (ajuste conforme necessário)
